const movies = [
    {
      id: 1,
      title: "Sense 8",
      description: "Ocho desconocidos tienen una conexión y comparten sentimientos y habilidades a medida que tratan de evitar su exterminio.",
      rating: 5.0,
      clasification: "18+",
      image: {
        banner: "https://i.blogs.es/712c37/sense8navidad2/1366_2000.jpg",
        card: "https://static.wikia.nocookie.net/sensate/images/3/39/Sense8_S1Poster_01.jpg/revision/latest?cb=20180616215114&path-prefix=es",
      },
      section: "recommended",           
    },
    {
      id: 2,
      title: "Lion",
      description: "Saroo, un niño indio de 5 años, se perdió viajando en tren y tuvo que aprender a sobrevivir en las calles de Calcuta hasta que fue adoptado por una pareja australiana. Con 25 años y armado solo con sus recuerdos, una fe inquebrantable y un navegador, regresa a la India para encontrar a su familia biológica.",
      rating: 4.4,
      clasification: "14+",
      image: {
        banner: "https://ic.c4assets.com/brands/lion/a14485fb-09e5-4f81-9a45-a05b970f4f91.jpg?interpolation=progressive-bicubic&output-format=jpeg&output-quality=90{&resize}",
        card: "https://adoptionsupport.org/wp-content/uploads/2017/01/Lion-movie-image.png",
      },
      section: "recommended",
    },
    {
      id: 3,
      title: "El gran hotel budapest",
      description: "El conserje de un elegante hotel europeo inicia una interesante amistad con un joven compañero de trabajo.",
      rating: 4.6,
      clasification: "13+",
      image: {
        banner: "https://2.bp.blogspot.com/-nW4L-VhjKJ8/VKv-xzQOErI/AAAAAAAAAoE/QkwEkPfS6ns/s1600/Fiennes-Ronan-y-Revolori.jpg",
        card: "https://cdn.hobbyconsolas.com/sites/navi.axelspringer.es/public/media/image/2016/12/gran-hotel-budapest.jpg?tf=3840x",
      },
      section: "recommended",
    },
    {
      id: 4,
      title: "Anne with an e",
      description: "En la década de 1890, una niña huérfana de 13 años es enviada por error a vivir con hermanos mayores a la Isla del Príncipe Eduardo.",
      rating: 4.8,
      clasification: "10+",
      image: {
        banner: "https://i.ytimg.com/vi/xehR6kOGh_8/maxresdefault.jpg",
        card: "https://m.media-amazon.com/images/M/MV5BNThmMzJlNzgtYmY5ZC00MDllLThmZTMtNTRiMjQwNmY0NmRhXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_FMjpg_UX1000_.jpg",
      },
      section: "recommended",
    },
    {
      id: 5,
      title: "Cloud atlas",
      description: "Varias historias se desarrollan en diversas líneas temporales, pero, aunque son independientes y tienen lugar a lo largo de cinco siglos, todas están relacionadas y repercuten en las demás, lo que desata drama, misterio, acción y amor.",
      rating: 4.0,
      clasification: "18+",
      image: {
        banner: "https://soniaunleashed.com/wp-content/uploads/2013/02/cloud_atlas_poster_7.jpg?w=529",
        card: "https://m.media-amazon.com/images/M/MV5BMTczMTgxMjc4NF5BMl5BanBnXkFtZTcwNjM5MTA2OA@@._V1_FMjpg_UX1000_.jpg",
      },
      section: "recommended",    
    },
    {
      id: 6,
      title: "La casa de papel",
      description: "Una banda organizada de ladrones se propone cometer el atraco del siglo en la Fábrica Nacional de Moneda y Timbre. Cinco meses de preparación quedarán reducidos a once días para poder llevar a cabo con éxito el gran golpe.",
      rating: 4.7,
      clasification: "18+",
      image: {
        banner: "https://sm.ign.com/ign_es/screenshot/default/20609360-84ea-4f54-8bf7-72836245cf85_8mje.jpg",
        card: "https://pics.filmaffinity.com/la_casa_de_papel-844739080-mmed.jpg",
      },
      section: "recommended",   
    },
    {
      id: 7,
      title: "Harry Potter y el prisionero de azkaban",
      description: "El tercer año de estudios de Harry en Hogwarts se ve amenazado por la fuga de Sirius Black de la prisión de Azkaban. Al parecer, se trata de un peligroso mago que fue cómplice de Lord Voldemort y que intentará vengarse de Harry Potter.",
      rating: 4.6,
      clasification: "8+",
      image: {
        banner: "https://hips.hearstapps.com/hmg-prod/images/harry-ron-hermione-el-prisionero-de-azkaban-642c07930e0c0.jpg?crop=1xw:0.8438818565400844xh;center,top&resize=1200:*",
        card: "https://cdn.hobbyconsolas.com/sites/navi.axelspringer.es/public/media/image/2016/11/harry-potter-prisionero-azkaban_0.jpg?tf=3840x",
      },
      section: "recommended",   
    },
    {
      id: 8,
      title: "El viaje de Chihiro",
      description: "Chihiro es una niña caprichosa que debe adentrarse en un mundo de fantasía para poder salvar a sus padres, convertidos en cerdos.",
      rating: 4.9,
      clasification: "5+",
      image: {
        banner: "https://static.eldiario.es/clip/d06079a3-c5b1-4af1-95d4-029eee91ca6c_16-9-aspect-ratio_default_0.jpg",
        card: "https://es.web.img2.acsta.net/pictures/21/05/11/13/47/5979708.jpg",
      },
      section: "recommended",   
    },
    {
      id: 9,
      title: "Dark",
      description: "La desaparición de dos niños muestra los vínculos entre cuatro familias y expone el pasado de una pequeña ciudad.",
      rating: 4.7,
      clasification: "18+",
      image: {
        banner: "https://dark.netflix.io/share/global.png",
        card: "https://m.media-amazon.com/images/M/MV5BOTk2NzUyOTctZDdlMS00MDJlLTgzNTEtNzQzYjFhNjA0YjBjXkEyXkFqcGdeQXVyMjg1NDcxNDE@._V1_.jpg",
      },
      section: "trending",   
    },
    {
      id: 10,
      title: "Isla de perros",
      description: "El alcalde de una ciudad japonesa decreta que, con motivo de una epidemia de gripe canina, todos los perros deben quedar confinados en una isla. Un niño de 12 años emprende una aventura para llegar hasta la isla y rescatar a su mascota..",
      rating: 4.2,
      clasification: "8+",
      image: {
        banner: "https://fancine.org/wp-content/uploads/2023/06/Isle-of-Dogs.jpg",
        card: "https://pics.filmaffinity.com/Isla_de_perros-102351400-large.jpg",
      },
      section: "trending",
    },
    {
        id: 11,
        title: "Orgullo y prejuicio",
        description: "Elizabeth Bennet conoce al apuesto y adinerado Sr. Darcy, con quien, rápidamente, inicia una intensa y compleja relación.",
        rating: 4.3,
       clasification: "13+",
        image: {
          banner: "https://play-lh.googleusercontent.com/proxy/luVn7MbGt8BoT0FGS74kO3RcbrljEIvSrtEZuuUi9nj3E_K7hfO76VOLSXj-1bE7_kQRxJNG99f9woCNnJS1k6-QlA6sKRqUaYFsXqKP1vQWhvzc9xBr=s1920-w1920-h1080",
          card: "https://pics.filmaffinity.com/Orgullo_y_prejuicio-629327318-large.jpg",
        },
        section: "trending",
      },
      {
        id: 12,
        title: "Stranger Things",
        description: "Cuando un niño desaparece, sus amigos, la familia y la policía se ven envueltos en una serie de eventos misteriosos al tratar de encontrarlo. Su ausencia coincide con el avistamiento de una criatura terrorífica y la aparición de una extraña niña.",
        rating: 4.7,
       clasification: "13+",
        image: {
          banner: "https://media-cldnry.s-nbcnews.com/image/upload/rockcms/2023-08/stranger-things-season-4-230816-01-d6669a.jpg",
          card: "https://cloudfront-us-east-1.images.arcpublishing.com/semana/JQUMFMWT4BBENIKIBXJHNNEJJI.jpg",
        },
        section: "trending",
      },
      {
        id: 13,
        title: "His Dark Materials",
        description: "Durante la búsqueda de una amiga secuestrada, una joven valiente de otro mundo revela un plan siniestro que involucra a niños desaparecidos y un fenómeno misterioso llamado Dust.",
        rating: 4.0,
       clasification: "13+",
        image: {
          banner: "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F6%2F2020%2F12%2F23%2FHis-Dark-Materials_1.jpg&q=60",
          card: "https://resizing.flixster.com/AhvQ60Z9S9YD671WnP4_e1LNxlg=/ems.cHJkLWVtcy1hc3NldHMvdHZzZWFzb24vUlRUVjc3MDcxOS53ZWJw",
        },
        section: "trending",
      },
      {
        id: 14,
        title: "El resplandor",
        description: "Jack Torrance se convierte en cuidador de invierno en el Hotel Overlook, en Colorado, con la esperanza de vencer su bloqueo con la escritura. Se instala allí junto con su esposa, Wendy, y su hijo, Danny, que está plagado de premoniciones psíquicas. Mientras la escritura de Jack no fluye y las visiones de Danny se vuelven más preocupantes, Jack descubre oscuros secretos del hotel y comienza a convertirse en un maníaco homicida, empeñado en aterrorizar a su familia.",
        rating: 4.5,
       clasification: "13+",
        image: {
          banner: "https://pics.filmaffinity.com/the_shining-194129791-large.jpg",
          card: "https://www.hobbyconsolas.com/sites/navi.axelspringer.es/public/media/image/2016/11/resplandor.jpg",
        },
        section: "trending",
      },
      {
        id: 15,
        title: "El increíble castillo vagabundo",
        description: "Después de que una bruja la transforma en una anciana, una fabricante de sombreros busca refugio en la casa ambulante de un singular mago.",
        rating: 4.0,
       clasification: "13+",
        image: {
          banner: "https://ramenparados.com/wp-content/uploads/2016/01/castillo-ambulante-1-1000x600.jpg",
          card: "https://es.web.img3.acsta.net/medias/nmedia/18/80/29/24/20062836.jpg",
        },
        section: "trending",
      },
      {
        id: 16,
        title: "El Señor de los Anillos: las dos torres",
        description: "Gollum guía a Frodo y Sam a Mordor mientras Aragorn y sus compañeros defienden a Rohan del bestial ejército de Saruman.",
        rating: 5.0,
       clasification: "13+",
        image: {
          banner: "https://w0.peakpx.com/wallpaper/921/750/HD-wallpaper-movie-the-lord-of-the-rings-the-lord-of-the-rings-the-two-towers.jpg",
          card: "https://es.web.img3.acsta.net/medias/nmedia/18/89/85/69/20070008.jpg",
        },
        section: "trending",
      },
];